version: "3"

networks:
  hyperkube: {}

services:
  etcd:
    image: gcr.io/google_containers/etcd:2.3.7
    networks:
      - hyperkube
    command: ['/usr/local/bin/etcd', '--addr=127.0.0.1:4001', '--bind-addr=0.0.0.0:4001', '--data-dir=/var/etcd/data']

  master:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    networks:
      - hyperkube
    privileged: true
    ports:
      - 8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
    command: ['/hyperkube', 'kubelet', '--hostname-override=127.0.0.1', '--address=0.0.0.0', '--api-servers=http://localhost:8080', '--enable-server', '--config=/etc/kubernetes/manifests', '--containerized', '--v=2']

  proxy:
    image: gcr.io/google_containers/hyperkube-amd64:v1.8.5
    networks:
      - hyperkube
    pid: host
    privileged: true
    command: ['/hyperkube', 'proxy', '--master=http://127.0.0.1:8080', '--v=2']