version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install virtualenv
            make dev-env
      - run:
          name: lint tests
          command: |
            make lint
