version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
      - image: registry:2
        name: registry
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Installing lint dependencies
          command: |
            # get python3 for tox
            apt-get update -y
            apt-get install -y software-properties-common
            add-apt-repository -y ppa:deadsnakes/ppa
            apt-get update -y
            apt-get install -y python python-pip python3
            # python3-venv is necessary or else venv initialization fails
            # see alternate answer on https://stackoverflow.com/questions/39539110/pyvenv-not-working-because-ensurepip-is-not-available
            apt-get install -y python3 python3-pip python3-venv
            python2 -m pip install virtualenv
            python3 -m pip install virtualenv tox

      - run:
          name: lint tests
          command: |
            make lint
      
      - run:
          name: Run unit tests
          command: |
            make test

      - run:
          name: Installing dependencies
          command: |
            set -x
            apt-get install -y curl make git ssh tar python
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            curl -L https://github.com/docker/compose/releases/download/1.16.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run e2e tests
          command: |
            make test-e2e
