version: 2
jobs:
  build:
    docker:
      - image: ubuntu:16.04
      - image: registry:2
        name: registry
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Installing test/lint dependencies
          command: |
            # get python3 for tox
            apt-get update
            apt-get install -yq --no-install-recommends --fix-missing \
                # apt-transport-https \
                # ca-certificates \
                curl \
                # git \
                # jq \
                make \
                # netcat \
                python \
                python-dev \
                python-pip \
                python-setuptools \
                python-wheel \
                python3 \
                python3-dev \
                python3-pip \
                python3-setuptools \
                python3-venv \
                python3-wheel \
                # ssh \
                tar
            # python3-venv is necessary or else venv initialization fails
            # see alternate answer on https://stackoverflow.com/questions/39539110/pyvenv-not-working-because-ensurepip-is-not-available
            python3 -m pip install tox

      - run:
          name: lint tests
          command: |
            make lint
      
      - run:
          name: Run unit tests
          command: |
            make test

      - run:
          name: Installing docker dependencies
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
            curl -L https://github.com/docker/compose/releases/download/1.16.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
            chmod +x /usr/local/bin/docker-compose

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Run e2e tests
          command: |
            make test-e2e
